[project]
name = "EpoxyDesign"
version = "4.0.0"
description = "Epoxy composite design through machine learning"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "dragon-ml-toolbox[ml]==20.14.1",
]

[dependency-groups]
dev = [
    "nbstripout>=0.8.2",
]
